kryn_cms_admin:
    prefix: /kryn
    resource: "@KrynCmsBundle/Controller/Admin/"
    type:     annotation

kryn_cms_admin_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /kryn/doc