kryn_cms_admin_login:
    resource: "@KrynCmsBundle/Controller/Admin/LoginController.php"
    type:     annotation

kryn_cms_admin:
    prefix: /kryn
    resource: "@KrynCmsBundle/Controller/Admin/AdminController.php"
    type:     annotation