kryn_cms_admin_login:
    resource: "@KrynCmsBundle/Controller/AdminLoginController.php"
    type:     annotation

kryn_cms_admin:
    prefix: %kryn_admin_prefix%
    resource: "@KrynCmsBundle/Controller/Admin/"
    type:     annotation

kryn_cms_objects:
    resource: .
    type: kryn_rest