kryn_cms_admin_login:
    resource: "@KrynCmsBundle/Controller/AdminLoginController.php"
    type:     annotation

kryn_cms_admin:
    prefix: %kryn_admin_prefix%
    resource: "@KrynCmsBundle/Controller/Admin/"
    type:     annotation

kryn_cms_admin_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /kryn/doc2

kryn_cms_objects:
    resource: .
    type: kryn_rest