parameters:
     kryn_cms.core.class: Kryn\CmsBundle\Core
     kryn_cms.objects.class: Kryn\CmsBundle\Objects
     kryn_cms.cache.fast.factory.class: Kryn\CmsBundle\Cache\Factory
     kryn_cms.cache.fast.class: Kryn\CmsBundle\Cache\AbstractCache
     kryn_cms.content.render.class: Kryn\CmsBundle\ContentRender
     kryn_cms.routes.loader: Kryn\CmsBundle\Router\FrontendLoader
     kryn_cms.rest.routing_loader.class: Kryn\CmsBundle\Router\RestApiLoader

     kryn_cms.acl.class: Kryn\CmsBundle\ACL

     kryn_cms.navigation.class: Kryn\CmsBundle\Navigation
     kryn_cms.stopwatch.class: Kryn\CmsBundle\StopwatchHelper
     kryn_cms.translator.class: Kryn\CmsBundle\Translation\Translator

     kryn_cms.pluginResponse.listener.class: Kryn\CmsBundle\EventListener\PluginResponseListener
     kryn_cms.paramFetcher.listener.class: Kryn\CmsBundle\EventListener\ParamFetcherListener
     kryn_cms.securityFirewall.listener.class: Kryn\CmsBundle\EventListener\SecurityFirewallListener
     kryn_cms.restException.listener.class: Kryn\CmsBundle\EventListener\RestExceptionListener
     kryn_cms.viewResponse.listener.class: Kryn\CmsBundle\EventListener\ViewResponseListener
     kryn_cms.frontendRoutes.listener.class: Kryn\CmsBundle\EventListener\FrontendRouteListener
     kryn_cms.debugger.subscriber.class: Kryn\CmsBundle\EventListener\DebuggerSubscriber
     kryn_cms.latencyMonitor.subscriber.class: Kryn\CmsBundle\EventListener\LatencyMonitorSubscriber

     kryn_cms.page.response.class: Kryn\CmsBundle\PageResponse
     kryn_cms.logger.handler.class: Kryn\CmsBundle\Logger\KrynHandler

     kryn_cms.filesystem.local.class: Kryn\CmsBundle\Filesystem\Filesystem
     kryn_cms.filesystem.cache.class: Kryn\CmsBundle\Filesystem\Filesystem
     kryn_cms.filesystem.web.class: Kryn\CmsBundle\Filesystem\WebFilesystem
     kryn_cms.filesystem.adapter.local.class: Kryn\CmsBundle\Filesystem\Adapter\Local

     kryn_cms.model.builder.class: Kryn\CmsBundle\ORM\Builder\Builder
     kryn_cms.model.builder.propel.class: Kryn\CmsBundle\ORM\Builder\Propel

#     kryn_cms.configuration.class: Kryn\CmsBundle\Configuration\SystemConfig
     kryn_cms.configuration.database.class: Kryn\CmsBundle\Configuration\Database

     kryn_cms.configuration.database.connection.main.class: Kryn\CmsBundle\Configuration\Connection

     database_table_prefix: kryn_
     kryn_admin_prefix: /kryn

services:
     kryn_cms:
         class: %kryn_cms.core.class%
         arguments: ["@service_container"]

     kryn_cms.objects:
         class: %kryn_cms.objects.class%
         arguments: ["@kryn_cms"]

     kryn_cms.cache.fast:
         class: %kryn_cms.cache.fast.class%
         factory_class: %kryn_cms.cache.fast.factory.class%
         factory_method: createFast
         arguments: ["@kryn_cms"]

     kryn_cms.page.response:
         class: %kryn_cms.page.response.class%
         calls:
            - [setKrynCore, ["@kryn_cms"]]
            - [setStopwatch, ["@kryn_cms.stopwatch"]]

     kryn_cms.content.render:
         class: %kryn_cms.content.render.class%
         arguments: ["@kryn_cms", "@kryn_cms.stopwatch"]
#
#     kryn_cms.configuration:
#         class: %kryn_cms.configuration.class%
#         calls:
#            - [setDatabase, ["@kryn_cms.configuration.database"]]
#            - [setKrynCore, ["@kryn_cms"]]

     kryn_cms.configuration.database:
         class: %kryn_cms.configuration.database.class%
         calls:
            - [addConnection, ["@kryn_cms.configuration.database.connection.main"]]
            - [setPrefix, ["%database_table_prefix%"]]

     kryn_cms.configuration.database.connection.main:
         class: %kryn_cms.configuration.database.connection.main.class%
         calls:
            - [setType, ["%database_driver%"]]
            - [setServer, ["%database_host%"]]
            - [setPort, ["%database_port%"]]
            - [setName, ["%database_name%"]]
            - [setUsername, ["%database_user%"]]
            - [setPassword, ["%database_password%"]]

     kryn_cms.filesystem.adapter.local:
         class: %kryn_cms.filesystem.adapter.local.class%
         arguments: ["/"]
         calls:
             - [setRoot, ["%kernel.root_dir%/.."]]

     kryn_cms.filesystem.adapter.cache:
         class: %kryn_cms.filesystem.adapter.local.class%
         arguments: ["/"]
         calls:
             - [setRoot, ["%kernel.cache_dir%"]]

     kryn_cms.filesystem.local:
         class: %kryn_cms.filesystem.local.class%
         calls:
            - [setAdapter, ["@kryn_cms.filesystem.adapter.local"]]

     kryn_cms.filesystem.cache:
         class: %kryn_cms.filesystem.cache.class%
         calls:
            - [setAdapter, ["@kryn_cms.filesystem.adapter.cache"]]

     kryn_cms.filesystem.web:
         class: %kryn_cms.filesystem.web.class%
         arguments: ["@kryn_cms"]

     kryn_cms.navigation:
         class: %kryn_cms.navigation.class%
         arguments: ["@kryn_cms"]

     kryn_cms.pluginResponse.listener:
        class: %kryn_cms.pluginResponse.listener.class%
        arguments: ["@kryn_cms", "@kryn_cms.frontendRoutes.listener"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }
            - { name: kernel.event_listener, event: kernel.view }

     kryn_cms.paramFetcher.listener:
        class: %kryn_cms.paramFetcher.listener.class%
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, prioarity: 6 }

     kryn_cms.viewResponse.listener:
        class: %kryn_cms.viewResponse.listener.class%
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 101 }
            - { name: kernel.event_listener, event: kernel.controller, priority: -9 }

     kryn_cms.frontendRoutes.listener:
        class: %kryn_cms.frontendRoutes.listener.class%
        arguments: ["@kryn_cms"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 33 }

     kryn_cms.securityFirewall.listener:
        class: %kryn_cms.securityFirewall.listener.class%
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 21 }

     kryn_cms.restException.listener:
        class: %kryn_cms.restException.listener.class%
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception}

     kryn_cms.latencyMonitor.subscriber:
        class: %kryn_cms.latencyMonitor.subscriber.class%
        arguments: ["@kryn_cms"]
        tags:
            - { name: kernel.event_subscriber }

     kryn_cms.debugger.subscriber:
        class: %kryn_cms.debugger.subscriber.class%
        arguments: ["@kryn_cms", "@kryn_cms.logger.handler"]
        tags:
            - { name: kernel.event_subscriber }

     kryn_cms.translator:
        class: %kryn_cms.translator.class%
        arguments: ["@kryn_cms"]

     kryn_cms.stopwatch:
        class: %kryn_cms.stopwatch.class%
        arguments: ["@?debug.stopwatch"]

     kryn_cms.acl:
        class: %kryn_cms.acl.class%
        arguments: ["@kryn_cms", "@kryn_cms.objects"]

     kryn_cms.logger.handler:
        class: %kryn_cms.logger.handler.class%
        arguments: ["@kryn_cms"]
        
     kryn_cms.rest.routing_loader:
        class: %kryn_cms.rest.routing_loader.class%
        arguments: ["@kryn_cms"]
        tags:
            - { name: routing.loader }

     kryn_cms.model.builder:
        class: %kryn_cms.model.builder.class%
        arguments: ["@kryn_cms.objects"]

     kryn_cms.model.builder.propel:
        class: %kryn_cms.model.builder.propel.class%
        arguments: [@kryn_cms.filesystem.local]
        tags:
            - { name: kryn_cms.model.builder, alias: propel }