parameters:
     kryn.content.types.class: Kryn\CmsBundle\ContentTypes\ContentTypes
     kryn.content.types.text.class: Kryn\CmsBundle\ContentTypes\TypeText
     kryn.content.types.plugin.class: Kryn\CmsBundle\ContentTypes\TypePlugin
     kryn.content.types.markdown.class: Kryn\CmsBundle\ContentTypes\TypeMarkdown

services:
     kryn.content.types:
         class: %kryn.content.types.class%

     kryn.content.types.text:
         class: %kryn.content.types.text.class%
         tags:
             - { name: kryn.content.type, alias: text }

     kryn.content.types.plugin:
         class: %kryn.content.types.plugin.class%
         arguments: ["@kryn.cms"]
         tags:
             - { name: kryn.content.type, alias: plugin }

     kryn.content.types.markdown:
         class: %kryn.content.types.markdown.class%
         arguments: ["@kryn.cms"]
         tags:
             - { name: kryn.content.type, alias: markdown }