parameters:
     kryn_cms.content.types.class: Kryn\CmsBundle\ContentTypes\ContentTypes
     kryn_cms.content.types.text.class: Kryn\CmsBundle\ContentTypes\TypeText
     kryn_cms.content.types.image.class: Kryn\CmsBundle\ContentTypes\TypeImage
     kryn_cms.content.types.plugin.class: Kryn\CmsBundle\ContentTypes\TypePlugin
     kryn_cms.content.types.markdown.class: Kryn\CmsBundle\ContentTypes\TypeMarkdown
     kryn_cms.content.types.tray.class: Kryn\CmsBundle\ContentTypes\TypeTray

services:
     kryn_cms.content.types:
         class: %kryn_cms.content.types.class%

     kryn_cms.content.types.text:
         class: %kryn_cms.content.types.text.class%
         tags:
             - { name: kryn_cms.content.type, alias: text }

     kryn_cms.content.types.image:
         class: %kryn_cms.content.types.image.class%
         arguments: ["@kryn_cms"]
         tags:
             - { name: kryn_cms.content.type, alias: image }

     kryn_cms.content.types.plugin:
         class: %kryn_cms.content.types.plugin.class%
         arguments: ["@kryn_cms"]
         tags:
             - { name: kryn_cms.content.type, alias: plugin }

     kryn_cms.content.types.markdown:
         class: %kryn_cms.content.types.markdown.class%
         arguments: ["@kryn_cms"]
         tags:
             - { name: kryn_cms.content.type, alias: markdown }

     kryn_cms.content.types.tray:
         class: %kryn_cms.content.types.tray.class%
         arguments: ["@kryn_cms.content.render"]
         tags:
             - { name: kryn_cms.content.type, alias: tray }